-- .luacheckrc
std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "212/self", "611", "612", "613", "614", "621" } -- implicit self (house ns: methods) + whitespace, StyLua owns the latter
exclude_files = { "Includes/" } -- vendored, never linted
read_globals = {
	"BANK_CONTAINER",
	"BankFrame",
	"C_AddOns",
	"C_Container",
	"C_EventUtils",
	"C_Item",
	"C_QuestLog",
	"C_Timer",
	"ClearCursor",
	"CreateFrame",
	"CursorHasItem",
	"DELETE_GOOD_ITEM",
	"DELETE_ITEM_CONFIRM_STRING",
	"DeleteCursorItem",
	"Enum",
	"GameTooltip",
	"GetAddOnInfo",
	"GetAddOnMetadata",
	"GetBuildInfo",
	"GetCVar",
	"GetCursorInfo",
	"GetItemInfo",
	"GetItemInfoInstant",
	"GetItemQualityColor",
	"GetLocale",
	"GetNumAddOns",
	"GetPhysicalScreenSize",
	"GetTime",
	"InCombatLockdown",
	"IsShiftKeyDown",
	"LibStub",
	"MailFrame",
	"MerchantFrame",
	"NO",
	"NUM_BAG_SLOTS",
	"NUM_BANKBAGSLOTS",
	"PlaySound",
	"SetCVar",
	"Settings",
	"StaticPopup1",
	"StaticPopup_FindVisible",
	"StaticPopup_Show",
	"TooltipDataProcessor",
	"UIParent",
	"UnitClass",
	"UnitLevel",
	"UnitRace",
	"WOW_PROJECT_ID",
	"YES",
	"bit",
	"hooksecurefunc",
	"wipe",
}
globals = {
	"MagicEraserDB",
	"SLASH_MAGICERASER1",
	"SlashCmdList",
	"StaticPopupDialogs",
}
